# Test Run: metrics.tests.test_permanent_computations.test_serializersclea

Total tests: 1
Passed: 0
Failed: 0
Errors: 1

## test_serializersclea (unittest.loader._FailedTest)
Status: error
Duration: 0.004 seconds

### Error
```
ImportError: Failed to import test module: test_serializersclea
Traceback (most recent call last):
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'metrics.tests.test_permanent_computations.test_serializersclea'

```

### Output
```
2024-08-07 16:37:26,929 - metrics - DEBUG - Starting test: test_serializersclea (unittest.loader._FailedTest)
```

